spring:
  application:
    name: ACbaord

#Database
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#mybatis:
#  mapper-locations: classpath:/mybatis/mappers/*.xml
#  config-location: classpath:/mybatis/config.xml
server:
  servlet:
    jsp:
      init-parameters:
        development=true: true
  port: 9000

logging:
  level:
    org:
      springframework:
        security=DEBUG: