spring:
  application:
    name: ACboard
#DB
  datasource:
    url: jdbc:mysql://localhost:3306/board
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
#JSP
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#File
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#Mybatis
mybatis:
    mapper-locations: classpath:/mybatis/mappers/*.xml
    config-location: classpath:/mybatis/config.xml
#
server:
  servlet:
    jsp:
      init-parameters:
        development: true

jwt:
    secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa